name: CI

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: '1.24'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Lint
        uses: golangci/golangci-lint-action@v8

      - name: Build
        run: go build -v ./...

      - name: Add to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openapi-oathkeeper
          path: ./openapi-oathkeeper